site_name: Jumble documentation
site_url: https://lguez.github.io/Jumble
repo_url: https://github.com/lguez/Jumble
site_author: Lionel GUEZ
nav:
   - index.md
   - detailed_content.md
   - NR_util.md
   - installation.md
   - usage.md
theme: readthedocs
markdown_extensions:
   - footnotes
